### ISSUE TITLE
AuthClient.refresh() does not return new refresh_token

### ISSUE THREAD

**Issue by jaredthecoder** [intuit/oauth-pythonclient#17]
Hi, I am running into an issue where `AuthClient.refresh` does not return a new refresh token, just a new access token. This goes against the behavior specified in the docs an in this Intuit Developer Forum post: https://help.developer.intuit.com/s/question/0D50f00006Kfd2X/refreshtokenasync-returning-invalidgrant.

Code:

```
old_access_token = client.auth_client.access_token
old_refresh_token = client.auth_client.refresh_token

client.auth_client.refresh(refresh_token=client.auth_client.refresh_token)

new_access_token = client.auth_client.access_token
new_refresh_token = client.auth_client.refresh_token

if old_access_token == new_access_token:
   raise ValueError('Access token has not been changed after refresh!')

if old_refresh_token == new_refresh_token:
    # Exception raised here
    raise ValueError('Refresh token has not been changed after refresh!')

store_new_tokens(access_token, refresh_token)
```

**Comment by jaredthecoder** [comment]
My package version is 1.2.3 and python version is 3.7.4.

**Comment by furious-luke** [comment]
We're experiencing the same issue, and it's a bit of a show-stopper for us. We have refresh tokens reaching the 100 day limit, any information about why the refresh token and its expiry is failing to update would be greatly appreciated.

**Comment by fjolin-intuit** [comment]
Hi @jaredthecoder and @furious-luke.  I believe you are experiencing expected behavior - The refresh tokens have a 100 day validity but can rotate anywhere from 24-26 hours.  So when you make a call to refresh your access token a day or two later - you could get back a new refresh token as well.  So essentially you won't always get new refresh tokens - but anytime you make a call to refresh tokens - you should store the latest refresh token response and use that to make subsequent refresh calls. 

**Examples:**
Let's say the company you have an access token for hasn't made a call to our APIs in 99 days - so both the access and refresh tokens are 99 days old.  This means that the access token is well over its expiration of 60 minutes.  But the refresh token is still valid as it expires after 100 days.  When you make a call to refresh you will get back a **new** access token and a **new** refresh token. 

Lets say you've been making calls every hour for two days.  every hour you refreshed tokens.  If you go back and look at the history of what our oauth servers sent back - you'll see 48 unique access_tokens and 2 unique refresh_tokens (because we rotate the refresh tokens every 24-26 hours or so).  

As this isn't unique to Python - if you have any further follow up questions could you submit a support ticket on our portal with details? https://help.developer.intuit.com/s/contactsupport

**Comment by furious-luke** [comment]
@fjolin-intuit Sorry for being unclear, but we have been calling to get new access tokens every day for 99 days now. By that logic, the refresh token should have been updated 97 days ago, but it hasn't. One of our refresh tokens is now within a day of expiry even after calling out for new refresh tokens every day.

**Comment by hlu2** [comment]
Hi @furious-luke  This may help. Go to https://help.developer.intuit.com/s/faqs , there is one authentication section. It has all the information you need.

**Comment by furious-luke** [comment]
@hlu2 Thanks for the link, I've been through that documentation, many forum posts, and have been in contact with Intuit technical team.

Would yourself or or @fjolin-intuit be able to help explain what might be going wrong in the example I mentioned? I'll go over it in more detail:

We have a lot of refresh tokens from many connected businesses. We run a task to ensure that *every day* we update every connection's access and refresh tokens. We also keep track of the reported refresh token expiry. We have seen that the newly returned refresh tokens *do not have a new expiry date*.

So, we will call the v1/token/bearer endpoint for a refresh token expiring within 10 days. We get back a new access token, and a refresh token that *is still expiring in 10 days*. Can you elaborate on why this might be the case?

Thanks for your help

**Comment by hlu2** [comment]
@furious-luke  It shouldn't expire in 10 days. Do you have an example? The best practice is, store the access token in the session, store the refresh token in your database. You do not need to track the expiration time. Simply send a request using the access token stored in the session, if you see a 401, refresh the access token using the refresh token in your database. When you make a refresh token API call, update the refresh token in your database(regardless of what value is returned).

**Comment by hantswilliams** [comment]
@jaredthecoder:i was running into a similar issue with python - pulling my hair out - i use a combination of intuit-oauth and python-quickbooks. what worked for me, first setting the variables: 

```
client_id={insert_here}
client_secret={insert_here}
environment='production'
redirect_uri={insert_here}
```
then creating the auth_client and following the refresh token: 

```
auth_client = AuthClient(client_id, client_secret, redirect_uri, environment)
new_token = auth_client.refresh_token
```

----- the above then successfully generated a new refresh token, I THEN create my client module with the following: 

```
client = QuickBooks(
        auth_client=auth_client,
        refresh_token=new_token,
        company_id={insert_here})
```

**Comment by allidoisace** [comment]
I'm experiencing the same thing till this day and it seems like even though we get a new access token and refresh token by comparison before and after a `.refresh()` call, the `AuthClient` object isn't updating `x_refresh_token_expires_in` correctly. Like OP said, through all the documentation you shouldn't need to have users re-authenticate if they are getting a new refresh token every day.
